name: Elixir CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.14.0'
        otp-version: '25.1.1'

    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: deps-${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: deps-${{ runner.os }}-mix-

    - name: Restore build cache
      uses: actions/cache@v2
      with:
        path: _build/test/
        key: build-${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: build-${{ runner.os }}-mix-

    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        mix compile

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mix coveralls.github
