name: Publish to Hex

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish to Hex
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.14.0'
        otp-version: '25.1.1'

    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: deps-${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: deps-${{ runner.os }}-mix-

    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix do deps.get, deps.compile

    - name: Build Hex package
      run: mix hex.build

    - name: Publish
      env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
      run: mix hex.publish --yes
